version: '3'
services:
  web:
    build:
      context: .
    command: yarn run start:dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
