version: '3'
services:
  web:
    build:
      context: .
    command: yarn run start:dev
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  pgadmin4:
    image: dpage/pgadmin4
    ports:
        - 8888:80
    volumes:
        - pgadmin:/var/lib/pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: ihatov08@gmail.com
        PGADMIN_DEFAULT_PASSWORD: password
    logging:
      driver: "none"
    depends_on:
      - db
volumes:
  node_modules:
  pgadmin:
