version: '3'
services:
  api:
    build:
      context: .
    command: yarn run start:dev
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
      POSTGRES_USERNAME: postgres
      POSTGRES_DATABASE: task-management
    depends_on:
      - db
    networks:
      - task_management_network
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - task_management_network
  pgadmin4:
    image: dpage/pgadmin4
    ports:
        - 8888:80
    volumes:
        - pgadmin:/var/lib/pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: ihatov08@gmail.com
        PGADMIN_DEFAULT_PASSWORD: password
    logging:
      driver: "none"
    depends_on:
      - db
    networks:
      - task_management_network
volumes:
  node_modules:
  pgadmin:
networks:
  task_management_network:
    external: true